version: "1"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    entrypoint:
      - ./entrypoint.sh
    environment:
      - TZ=Europe/Kaliningrad
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - web
      - db
    ports:
      - "80:80"
    volumes:
      - ./static/:/static

volumes:
  pgdata: